vision_model:
  name: "resnet50"
  pretrained: False
  embed_dim: 768

text_model:
  name: "openai/clip-vit-base-patch32"
  tokenizer: "openai/clip-vit-base-patch32"
  pretrained: False
  vocab_size: 49408
  embed_dim: 768
  n_hidden_layers: 12
  n_attention_heads: 8
  max_token_length: 77

projection_dim: 512
