vision_model:
  name: "openai/clip-vit-large-patch14"
  pretrained: True
  embed_dim: 1024

text_model:
  name: "openai/clip-vit-large-patch14"
  tokenizer: "openai/clip-vit-large-patch14"
  pretrained: True
  embed_dim: 768
  max_token_length: 77

projection_dim: 512
