vision_model:
  name: "openai/clip-vit-base-patch32"
  pretrained: True
  embed_dim: 768

text_model:
  name: "openai/clip-vit-base-patch32"
  tokenizer: "openai/clip-vit-base-patch32"
  pretrained: True
  embed_dim: 512
  max_token_length: 77

projection_dim: 512
